name: PHP

on:
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download files from Git
      uses: actions/checkout@v3
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: curl
      
#      run: |
#        sudo apt update
#        sudo apt install php php-curl

    - name: Check PHP
      run: php -v

    - name: Copy files
      run: ls  -la
